create table cases
(
    case_id         integer         generated by default as identity primary key,
    name            varchar(255)    unique,
    producer        varchar(255)    not null,
    motherboard     varchar(255)    not null,
    gpu_size        varchar(255)    not null,
    power_supply    varchar(255)    not null
);

alter table cases owner to postgres;

create table cpus
(
    cpu_id          integer          generated by default as identity primary key,
    name            varchar(255)     not null unique,
    producer        varchar(255)     not null,
    cores           integer          not null,
    threads         integer          not null,
    base_clock      varchar(255)     not null,
    socket          varchar(255)     not null,
    integral_gpu    varchar(255)     not null,
    tdp             varchar(255)     not null
);

alter table cpus owner to postgres;

create table gpus
(
    gpu_id          integer         generated by default as identity primary key,
    name            varchar(255)    not null unique,
    producer        varchar(255)    not null,
    gpuSize          varchar(255)    not null,
    vram            integer         not null,
    tdp             varchar(255)    not null
);

alter table gpus owner to postgres;

create table motherboards
(
    mb_id           integer         generated by default as identity primary key,
    name            varchar(255)    not null unique,
    producer        varchar(255)    not null,
    socket          varchar(255)    not null,
    form_factor     varchar(255)    not null,
    memory_type     varchar(255)    not null,
    memory_capacity integer         not null,
    memory_slots    integer         not null
);

alter table motherboards owner to postgres;

create table power
(
    power_id        integer         generated by default as identity primary key,
    name            varchar(255)    not null unique,
    watt            integer    not null,
    size            varchar(255)    not null
);

alter table power owner to postgres;

create table ram
(
    ram_id          integer         generated by default as identity primary key,
    name            varchar(255)    not null unique,
    ram_type        varchar(255)    not null,
    clock           varchar(255)    not null,
    size            varchar(255)    not null,
    sticks          integer         not null
);

alter table ram owner to postgres;

create table storage
(
    st_id           integer         generated by default as identity primary key,
    name            varchar(255)    not null unique,
    producer        varchar(255)    not null,
    size            integer         not null
);

alter table storage owner to postgres;

create table computer_setup
(
    case_id  integer not null
        constraint fkr268w5b9xtjhdx7fchtbp9bux
            references cases,
    cpu_id   integer not null
        constraint fknrwt9cnd8y04xqa82jk97t1rr
            references cpus,
    cs_id    integer generated by default as identity
        primary key,
    gpu_id   integer not null
        constraint fk8ss2bgilubj7nn02olvxyc11
            references gpus,
    mb_id    integer not null
        constraint fks5h5o93ippwklptpvvcu8o0as
            references motherboards,
    power_id integer not null
        constraint fk4dpc4dq0mbly824ieqlkanevt
            references power,
    ram_id   integer not null
        constraint fk3tc6pyd67sx88oeo16ig9bkbl
            references ram,
    st_id    integer not null
        constraint fkl26hk1yd39kbwl8iabj856jiw
            references storage,
    user_id  integer not null
        constraint fkn6c1o4p33qaljatv16a3lom36
            references users
);

alter table computer_setup
    owner to postgres;

create table types
(
    type_id integer generated by default as identity
        primary key,
    name    varchar(255) not null
        unique
);

alter table types
    owner to postgres;

create table users
(
    user_id  integer generated by default as identity
        primary key,
    email    varchar(255) not null
        unique,
    username varchar(255) not null,
    password varchar(255) not null,
    phone    varchar(255),
    photo    varchar(255)
);

alter table users
    owner to postgres;

create table likes_setup
(
    cs_id   integer not null
        constraint fk8ad9v1p7ohaglmsnvirigppws
            references computer_setup,
    like_id integer generated by default as identity
        primary key,
    user_id integer not null
        constraint fkhonjjpwscv38vb3ti6numno56
            references users
);

alter table likes_setup
    owner to postgres;

create table user_types
(
    type_id integer not null
        constraint fk963qrkftu4i1746omlqcy95g7
            references types,
    user_id integer not null
        constraint fkiaxlg5wn4xsgb8null7t6d7be
            references users,
    primary key (type_id, user_id)
);

alter table user_types
    owner to postgres;

create table user_setup
(
    cs_id   integer not null
        constraint fk61xbfamy2w7qisjhom0iu0doe
            references computer_setup,
    us_id   integer generated by default as identity
        primary key,
    user_id integer not null
        constraint fkqurgd7wjhanb3eka7euudhoyi
            references users
);

alter table user_setup
    owner to postgres;
