create table cases
(
    case_id   integer generated by default as identity
        primary key,
    price     double precision,
    case_type varchar(255) not null,
    gpu_size  varchar(255) not null,
    name      varchar(255)
        unique,
    producer  varchar(255) not null
        unique
);

alter table cases
    owner to postgres;

create table cpus
(
    base_clock varchar(255) not null,
    cores      integer          not null,
    cpu_id     integer generated by default as identity
        primary key,
    price      varchar(255),
    name       varchar(255)     not null
        unique,
    producer   varchar(255)     not null
        unique,
    socket     varchar(255)     not null
);

alter table cpus
    owner to postgres;

create table gpus
(
    gpu_id   integer generated by default as identity
        primary key,
    price    double precision,
    vram     integer      not null,
    producer   varchar(255)     not null,
    gpu_name varchar(255) not null
        unique,
    length   varchar(255) not null
);

alter table gpus
    owner to postgres;

create table motherboards
(
    mb_id           integer generated by default as identity
        primary key,
    memory_capacity integer      not null,
    memory_slots    integer      not null,
    price           double precision,
    form_factor     varchar(255) not null,
    memory_type     varchar(255) not null,
    name            varchar(255) not null
        unique,
    producer        varchar(255) not null
        unique,
    socket          varchar(255) not null
);

alter table motherboards
    owner to postgres;

create table power
(
    power_id integer generated by default as identity
        primary key,
    price    double precision,
    name     varchar(255) not null
        unique,
    watt     varchar(255) not null
);

alter table power
    owner to postgres;

create table ram
(
    price    double precision,
    ram_id   integer generated by default as identity
        primary key,
    size integer      not null,
    clock    varchar(255) not null,
    name     varchar(255) not null
        unique,
    producer varchar(255) not null,
    ram_type varchar(255) not null
);

alter table ram
    owner to postgres;

create table storage
(
    price    double precision,
    size     integer      not null,
    st_id    integer generated by default as identity
        primary key,
    name     varchar(255) not null
        unique,
    producer varchar(255) not null
);

alter table storage
    owner to postgres;

create table computer_setup
(
    case_id  integer not null
        constraint fkr268w5b9xtjhdx7fchtbp9bux
            references cases,
    cpu_id   integer not null
        constraint fknrwt9cnd8y04xqa82jk97t1rr
            references cpus,
    cs_id    integer generated by default as identity
        primary key,
    gpu_id   integer not null
        constraint fk8ss2bgilubj7nn02olvxyc11
            references gpus,
    mb_id    integer not null
        constraint fks5h5o93ippwklptpvvcu8o0as
            references motherboards,
    power_id integer not null
        constraint fk4dpc4dq0mbly824ieqlkanevt
            references power,
    ram_id   integer not null
        constraint fk3tc6pyd67sx88oeo16ig9bkbl
            references ram,
    st_id    integer not null
        constraint fkl26hk1yd39kbwl8iabj856jiw
            references storage
);

alter table computer_setup
    owner to postgres;

create table types
(
    type_id integer generated by default as identity
        primary key,
    name    varchar(255) not null
        unique
);

alter table types
    owner to postgres;

create table users
(
    user_id  integer generated by default as identity
        primary key,
    email    varchar(255) not null
        unique,
    nickname varchar(255) not null,
    password varchar(255) not null,
    phone    varchar(255) not null,
    photo    varchar(255)
);

alter table users
    owner to postgres;

create table likes_setup
(
    cs_id   integer not null
        constraint fk8ad9v1p7ohaglmsnvirigppws
            references computer_setup,
    like_id integer generated by default as identity
        primary key,
    user_id integer not null
        constraint fkhonjjpwscv38vb3ti6numno56
            references users
);

alter table likes_setup
    owner to postgres;

create table user_types
(
    type_id integer not null
        constraint fk963qrkftu4i1746omlqcy95g7
            references types,
    user_id integer not null
        constraint fkiaxlg5wn4xsgb8null7t6d7be
            references users,
    primary key (type_id, user_id)
);

alter table user_types
    owner to postgres;

create table user_setup
(
    cs_id   integer not null
        constraint fk61xbfamy2w7qisjhom0iu0doe
            references computer_setup,
    us_id   integer generated by default as identity
        primary key,
    user_id integer not null
        constraint fkqurgd7wjhanb3eka7euudhoyi
            references users
);

alter table user_setup
    owner to postgres;
