create table cases
(
    case_id      integer generated by default as identity
        primary key,
    gpu_size     integer      not null,
    motherboard  varchar(255) not null,
    name         varchar(255) not null,
    power_supply varchar(255) not null,
    producer     varchar(255) not null
);

alter table cases
    owner to postgres;

create table cpus
(
    base_clock   double precision,
    cores        integer      not null,
    cpu_id       integer generated by default as identity
        primary key,
    rank         integer,
    tdp          integer      not null,
    threads      integer      not null,
    integral_gpu varchar(255) not null,
    name         varchar(255) not null,
    producer     varchar(255) not null,
    socket       varchar(255) not null
);

alter table cpus
    owner to postgres;

create table game_requirements
(
    game_id        integer generated by default as identity
        primary key,
    hddspace       real         not null,
    min_ram        real         not null,
    mincpucore     real         not null,
    mincpuspeed    real         not null,
    mincputhread   real         not null,
    mingpuvram     real         not null,
    recom_ram      real         not null,
    recomcpucore   real         not null,
    recomcpuspeed  real         not null,
    recomcputhread real         not null,
    recomgpuvram   real         not null,
    name           varchar(255) not null
);

alter table game_requirements
    owner to postgres;

create table gpus
(
    gpu_id   integer generated by default as identity
        primary key,
    rank     integer,
    tdp      integer      not null,
    vram     integer      not null,
    gpu_size varchar(255) not null,
    name     varchar(255) not null,
    producer varchar(255) not null
);

alter table gpus
    owner to postgres;

create table motherboards
(
    mb_id           integer generated by default as identity
        primary key,
    memory_capacity integer      not null,
    memory_slots    integer      not null,
    form_factor     varchar(255) not null,
    memory_type     varchar(255) not null,
    name            varchar(255) not null,
    producer        varchar(255) not null,
    socket          varchar(255) not null
);

alter table motherboards
    owner to postgres;

create table power
(
    power_id integer generated by default as identity
        primary key,
    watt     integer      not null,
    name     varchar(255) not null,
    size     varchar(255) not null
);

alter table power
    owner to postgres;

create table program_requirements
(
    hddspace       real         not null,
    min_ram        real         not null,
    mincpucore     real         not null,
    mincpuspeed    real         not null,
    mincputhread   real         not null,
    mingpuvram     real         not null,
    program_id     integer generated by default as identity
        primary key,
    name           varchar(255) not null
);

alter table program_requirements
    owner to postgres;

create table ram
(
    ram_id   integer generated by default as identity
        primary key,
    rank     integer,
    size     double precision not null,
    sticks   integer          not null,
    clock    varchar(255)     not null,
    name     varchar(255)     not null,
    ram_type varchar(255)     not null
);

alter table ram
    owner to postgres;

create table storage
(
    rank     integer,
    size     integer      not null,
    st_id    integer generated by default as identity
        primary key,
    name     varchar(255) not null,
    producer varchar(255) not null
);

alter table storage
    owner to postgres;

create table types
(
    type_id integer generated by default as identity
        primary key,
    name    varchar(255) not null
        unique
);

alter table types
    owner to postgres;

create table users
(
    user_id  integer generated by default as identity
        primary key,
    email    varchar(255) not null
        unique,
    password varchar(255) not null,
    phone    varchar(255),
    photo    varchar(255),
    username varchar(255) not null
);

alter table users
    owner to postgres;

create table computer_setup
(
    case_id  integer not null
        constraint fkr268w5b9xtjhdx7fchtbp9bux
            references cases,
    cpu_id   integer not null
        constraint fknrwt9cnd8y04xqa82jk97t1rr
            references cpus,
    cs_id    integer generated by default as identity
        primary key,
    gpu_id   integer not null
        constraint fk8ss2bgilubj7nn02olvxyc11
            references gpus,
    mb_id    integer not null
        constraint fks5h5o93ippwklptpvvcu8o0as
            references motherboards,
    power_id integer not null
        constraint fk4dpc4dq0mbly824ieqlkanevt
            references power,
    ram_id   integer not null
        constraint fk3tc6pyd67sx88oeo16ig9bkbl
            references ram,
    st_id    integer not null
        constraint fkl26hk1yd39kbwl8iabj856jiw
            references storage,
    user_id  integer not null
        constraint fkn6c1o4p33qaljatv16a3lom36
            references users
);

alter table computer_setup
    owner to postgres;

create table rating_setup
(
    cs_id     integer          not null
        constraint fkdmg17v404xtv5s0tnllf96bsq
            references computer_setup,
    rating    double precision not null,
    rating_id integer generated by default as identity
        primary key,
    user_id   integer          not null
        constraint fk2rigab6fcitvrll2wrdpijhq8
            references users
);

alter table rating_setup
    owner to postgres;

create table saved_setup
(
    cs_id    integer not null
        constraint fk1reqm8h15jmv3nb6xycvhls2k
            references computer_setup,
    saved_id integer generated by default as identity
        primary key,
    user_id  integer not null
        constraint fk5lbdy28g1nydqdsekbs23mkod
            references users
);

alter table saved_setup
    owner to postgres;

create table user_types
(
    type_id integer not null
        constraint fk963qrkftu4i1746omlqcy95g7
            references types,
    user_id integer not null
        constraint fkiaxlg5wn4xsgb8null7t6d7be
            references users,
    primary key (type_id, user_id)
);

alter table user_types
    owner to postgres;
